#!/bin/bash

#	@file FIREWALL.sh
#	@Author Francisco Pablo, Rodrigo (14) && Cecilia (n) F.I. Ing. Computación PROTECO
#	@date 26/08/17
#	@brief Script para controlar el montaje de dispositivos USB

#El Punto del firewall es que la USB NO debe estar montada. 
#Porque al montarse, automaticamente el usuario queda vulnerado, por ello
#Deseactivamos los siguientes servicios el AUTOMONTADO

gsettings set org.gnome.desktop.media-handling automount false
#Este comando evita el automontado de la USB
gsettings set org.cinnamon.desktop.media-handling automount false
#Por si estamos en MINT
gsettings set org.gnome.desktop.media-handling automount-open true
#Auto-apertura de la USB LINUX UBUNTU
gsettings set org.cinnamon.desktop.media-handling automount-open true
#Por si estamos en MINT

mkdir /home/$USER/usb  #Crear la carpeta si es la primera vez
while [ 1 ]; do #Simulando presistencia con un while infinito
  cup=$(lsblk | grep "sd*[b-z]1")
  #Busca si hay alguna USB conectada y la guarda en la variabe cup
  er=""
  if [ "$cup" != "$er" ]; then    
  #Compara la cadena que tiene informacion de las USB con una cadena vacia
    echo "ALERTA! SE HA CONECTADO UNA USB A '$USER', QUE DESEA HACER:"
		echo "1) Montarla"
		echo "2) Enviar a la lista negra"
		echo "3) NO hacer nada" 
		echo -n "OP> "
		read opcion
			case $opcion in
				1 ) sudo mount /dev/sdb1 /home/$USER/usb 
					if [ $? -eq 0 ]; then
						echo "Se monto correctamente"
					fi ;;
			esac
	else
		echo "NO hay USB"
	fi
	sleep 2
done
####	Necesitamos enviar a la lista negra y verificar ue no este en la lista negra!
####	Probablemente necesitamos un cronometro.
####	Buscar que parametros se necesitan para montar un USB
##		Demonizar---> Podemos intentar con 
#		Si hay tiempo crear un script que descative el automontado 
#		SI NO especificar en el manual
#https://blog.desdelinux.net/script-para-espiar-el-contenido-de-dispositivos-usb-y-copiarlo-a-la-pc/
#Interfaz grafica = Cecilia
