#!/bin/bash
# Pseudocodigo firewall
##Ejecutar persistentemente!
##Verficar los puertos USB cada 5 segundos
Entrada de un dispositivo 
Si (Lista_negra y Lista_blanca estan vacias o Entrada no esta en Lista_blanca ni Lista_negra){ #Primera insercion del USB
    echo “Esta seguro de permitir el acceso al dispositivo insertado; podria ser un virus o algo peor”
    Recibir Si/No
    Si (Respuesta=Si)
       echo "Se agrego a la lista blanca"
       Agregar a lista blanca
       Montar dispositivo
    Si no 
	No montar
     	Agregar a la lista negra
     
}Si no{ #Mas de una insercion
	Si(Entrada está en Lista_blanca)
		Montar 
	Sino  
	Imprimir “Esta seguro de permitir el acceso al dispositivo  insertado; podria ser un virus o algo peor”
	Recibir Si/No
	Si (Respuesta=si)
		Borra de Lista_negra
		Agregar a Lista_blanca
		Montar 
	Sino 
		No montar
}
Fin del programa
#Aqui ya hay que poner el codigo no?
#pues estaba pensando en encimarlo 
