#!/bin/bash
#	@file FIREWALL.sh
#	@Author Francisco Pablo, Rodrigo (14) && Cecilia (n) F.I. Ing. Computación PROTECO
#	@date 26/08/17
#	@brief Script para controlar el montaje de dispositivos USB

#El Punto del firewall es que la USB NO debe estar montada. 
#Al montarse automaticamente el usuario queda vulnerado, por ello deseactivamos el AUTOMONTADO

gsettings set org.gnome.desktop.media-handling automount false
#Este comando evita el automontado de la USB
#gsettings set org.cinnamon.desktop.media-handling automount false
#Por si estamos en MINT
gsettings set org.gnome.desktop.media-handling automount-open true
#Auto-apertura de la USB LINUX UBUNTU
#gsettings set org.cinnamon.desktop.media-handling automount-open true
#Por si estamos en MINT

if [ ! -d /home/$USER/usb ]; then	
#Verfica si la carpeta donde vamos a montar NO exista
	mkdir /home/$USER/usb  
fi
if [ ! -f Blacklist.txt ]; then	
#Verifica que exista el archivo donde ingresamos los dispositivos bloqueados
	touch Blacklist.txt
fi
if [ ! -f Whitelist.txt ]; then 
#Verifica que exista el archivo donde ingresamos los dispositivos permitidos
        touch Whitelist.txt
fi
                
while [ 1 ]; do #Simulando presistencia con un while infinito
  cup=$(lsblk | grep "sd*[b-z]1")
  #Busca si hay alguna USB conectada y la guarda en la variabe cup
  er=""
  if [ "$cup" != "$er" ]; then    
  #Compara la cadena que tiene informacion de las USB con una cadena vacia
  	USBSERIAL=$(dmesg | tail -n20 | grep ": Serial" | awk '{print $6}' )
  	USBLABEL='USB-DEVICE'
  	if [ $(grep -c $USBSERIAL Whitelist.txt) == 1 ]; then
		sudo mount /dev/sdb1 /home/$USER/usb 
		zenity --info \
                --text="Permiso confirmado"
		break
	elif [ $(grep -c $USBSERIAL Blacklist.txt) == 0 ]; then
	    zenity --warning \
	    --text="ALERTA! SE HA CONECTADO el dispotivo  $USBLABEL al equipo '$USER."
	    opcion=$( zenity --width=320 --height=220 --title=Firewall --entry --text="Introduce una opcion: 
     	    1) Montarla
     	    2) Enviar a la lista negra 
     	    3) Salir ")
	    
###-----------------------------------------------------------------------------------------------------##
###-----------------------------------------------------------------------------------------------------##
    read opcion
    	case $opcion in
		1 ) sudo mount /dev/sdb1 /home/$USER/usb 
			if [ $? -eq 0 ]; then
				echo -e "Se monto correctamente\n"
			fi ;;
	esac
  else
  	echo -e "NO hay USB\n"
  fi
  sleep 2
done
####	Necesitamos enviar a la lista negra y verificar que no este en la lista negra!
####	Probablemente necesitamos un cronometro.
###	Demonizar---> Podemos intentar con 
#https://blog.desdelinux.net/script-para-espiar-el-contenido-de-dispositivos-usb-y-copiarlo-a-la-pc/
#	Interfaz grafica = Cecilia
