#!/bin/bash
# Pseudocodigo firewall
##Ejecutar persistentemente!
##Verficar los puertos USB cada 5 segundos
Entrada de un dispositivo 
if [ Lista_negra y Lista_blanca estan vacias o Entrada no esta en Lista_blanca ni Lista_negra ]; then #Primera insercion del USB
    echo “Esta seguro de permitir el acceso al dispositivo insertado, podria ser un virus o algo peor.”
    echo "Escoge Si o No"
    read respuesta
    if [ $respuesta = 'Si' ]; then
       echo "Se agrego a la lista blanca"
       Agregar a lista blanca
       Montar dispositivo
    else 
    	echo "Se agrego a la lista negra, lo que significa que no se ejecutara"
	No montar
     	Agregar a la lista negra
    fi
elif [ Entrada está en Lista_blanca ]; then #Mas de una insercion
		Montar 
	else  
	echo “Esta seguro de permitir el acceso al dispositivo  insertado ; podria ser un zombie o algo peor”
	echo "Escoge Si o No"
	read res
	if [ $res = 'Si' ]; then
		Borra de Lista_negra
		Agregar a Lista_blanca
		Montar 
	else
		No montar
	fi
	fi

Fin del programa
#Aqui ya hay que poner el codigo no?
#pues estaba pensando en encimarlo 
